encoding: utf-8
safe: false
highlighter: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /blog/:year/:month/:day/:title/
#paginate: 10          # Posts per page on the blog index
#pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/

# Directory
source: source
destination: dist
plugins: plugins
category_dir: blog

author:
  name: Makoto Kawasaki
  email: makoto.kw@gmail.com
  screen_name: makoto_kw
  github: makotokw
  twitter: makotokw
  twitter_ja: makoto_kw

# Domain
lang: en
title: makotokw.com
path:
url: http://makotokw.com
subscribe_url: http://makotokw.com/atom.xml
blog_ja_url: http://blog.makotokw.com
github_url: https://github.com/makotokw
qiita_url: http://qiita.com/makoto_kw
twitter_url: https://twitter.com/makotokw
twitter_ja_url: https://twitter.com/makoto_kw
linkedin_url: http://www.linkedin.com/in/makotokw
disqus_short_name: makotokw
google_analytics:
  account: UA-730110-3
  domain: makotokw.com
#download_url: /assets/downloads/
download_url: https://dl.dropboxusercontent.com/u/8932138/downloads/
addthis_profile_id: ra-51d5a54a1c992276

# Plugin: jekyll-assets
# https://github.com/ixti/jekyll-assets
# http://ixti.net/jekyll-assets/
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/components/javascripts
    - _assets/components/stylesheets
    - _assets/components/stylesheets
    - _assets/makotokw2015/javascripts
    - _assets/makotokw2015/stylesheets
    - _assets/makotokw2015/images
  compress:
    js:   ~
    css:  ~
  gzip: []
