# http://jekyllrb.com/docs/configuration/
development: false

# Where things are
source: ./source
destination: ./dist
plugins_dir: ./plugins

# Handling Reading
safe: false
encoding: utf-8

# Plugins
whitelist: []
gems:
  - jekyll-assets

# Conversion
markdown:    kramdown
highlighter: coderay
lsi:         false
excerpt_separator: "\n\n"

# Markdown Processors
# kramdown: http://kramdown.gettalong.org/rdoc/Kramdown/Options.html
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
kramdown:
  input:            GFM
  auto_ids:         false
  enable_coderay:   true

  coderay:
    coderay_tab_width:         2
    coderay_css:               style

# Outputting
permalink: /blog/:year/:month/:day/:title/

category_dir: blog

# Author
author:
  name: Makoto Kawasaki
  email: makoto.kw@gmail.com
  screen_name: makoto_kw
  github: makotokw
  twitter: makotokw
  twitter_ja: makoto_kw

# makotokw.com
lang: en
title: makotokw.com
path:
url: http://makotokw.com
subscribe_url: http://makotokw.com/atom.xml
blog_ja_url: http://blog.makotokw.com
github_url: https://github.com/makotokw
qiita_url: http://qiita.com/makoto_kw
twitter_url: https://twitter.com/makotokw
twitter_ja_url: https://twitter.com/makoto_kw
linkedin_url: http://www.linkedin.com/in/makotokw
disqus_short_name: makotokw
google_analytics:
  account: UA-730110-3
  domain: makotokw.com
#download_url: /assets/downloads/
download_url: https://dl.dropboxusercontent.com/u/8932138/downloads/
addthis_profile_id: ra-51d5a54a1c992276

# Plugin: jekyll-assets
# http://jekyll.github.io/jekyll-assets/
assets:
  sources:
    - _bower_components/bootstrap-sass/assets/stylesheets
    - _bower_components/bootstrap-material-design/sass
    - _bower_components/font-awesome/scss
    - _assets/components
    - _assets/makotokw2016/javascripts
    - _assets/makotokw2016/stylesheets
    - _assets/makotokw2016/images
  compress:
    js:   ~
    css:  ~
